### ISSUE TITLE
AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by mlix8hoblc** [JohnMwendwa/vet-management-system#76]
```
$ npm run dev

> vet-management-system@0.1.0 dev
> next dev

   ▲ Next.js 14.0.1
   - Local:        http://localhost:3000

 ✓ Ready in 9.3s
(node:19544) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ○ Compiling /page ...
The user aborted a request.

Retrying 1/3...
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
 ⨯ Failed to download `Inter` from Google Fonts. Using fallback font instead.

Failed to fetch `Inter` from Google Fonts.}
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:374:10)        
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (C:\Users\LENOVO\Desktop\vet-management-system\node_modules\next\dist\compiled\@next\font\dist\google\fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {       
  type: 'aborted'
}
(node:19544) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
 ✓ Compiled /page in 30.6s (1287 modules)
 ```

**Comment by JohnMwendwa** [comment]
Please read and follow the getting started guideline, for your case it seems you never added the environment variables as stipulated on the guideline  on how to [ADD ENVIRONMENT VARIABLES](https://github.com/JohnMwendwa/vet-management-system#getting-started-).

Add the environment variables and try running the app again

**Comment by mlix8hoblc** [comment]
For me, unstable internet connection was the issue (https://github.com/vercel/next.js/issues/45080#issuecomment-1598296425).
